//
//  JCStyleKit.h
//  JC
//
//  Created by Doug Leonard on 6/19/14.
//  Copyright (c) 2014 Jive. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface JCStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* speakerButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* trashButtonTargets;

// Drawing Methods
+ (void)drawSpeakerButtonWithSpeakerFrame: (CGRect)speakerFrame speakerIsSelected: (BOOL)speakerIsSelected;
+ (void)drawTrashButtonWithOuterFrame: (CGRect)outerFrame selectWithDeleteColor: (BOOL)selectWithDeleteColor;
+ (void)drawComposeIconWithFrame: (CGRect)frame;
+ (void)drawPlay_PauseWithFrame: (CGRect)frame playPauseDisplaysPlay: (BOOL)playPauseDisplaysPlay;
+ (void)drawCanvas1WithFrame: (CGRect)frame;
+ (void)drawCanvas3WithFrame: (CGRect)frame;
+ (void)drawCanvas5WithFrame: (CGRect)frame;
+ (void)drawCanvas2WithFrame: (CGRect)frame;
+ (void)drawCanvas4WithFrame: (CGRect)frame;
+ (void)drawCanvas6WithFrame: (CGRect)frame;
+ (void)drawCanvas7WithFrame: (CGRect)frame;
+ (void)drawCanvas8WithFrame: (CGRect)frame;
+ (void)drawCanvas9WithFrame: (CGRect)frame;
+ (void)drawCanvas10WithFrame: (CGRect)frame;
+ (void)drawCanvas11WithFrame: (CGRect)frame;
+ (void)drawCanvas12WithFrame: (CGRect)frame;
+ (void)drawCanvas13WithFrame: (CGRect)frame;
+ (void)drawCanvas14WithFrame: (CGRect)frame;
+ (void)drawCanvas15WithFrame: (CGRect)frame;
+ (void)drawCanvas16WithFrame2: (CGRect)frame2;

// Generated Images
+ (UIImage*)imageOfSpeakerButtonWithSpeakerFrame: (CGRect)speakerFrame speakerIsSelected: (BOOL)speakerIsSelected;
+ (UIImage*)imageOfTrashButtonWithOuterFrame: (CGRect)outerFrame selectWithDeleteColor: (BOOL)selectWithDeleteColor;

@end
