//
//  JCStyleKit.m
//  JC
//
//  Created by Doug Leonard on 5/27/14.
//  Copyright (c) 2014 Jive. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "JCStyleKit.h"


@implementation JCStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawSpeakerButtonWithSpeakerFrame: (CGRect)speakerFrame speakerIsSelected: (BOOL)speakerIsSelected;
{
    //// Color Declarations
    UIColor* unSelectedButtonColor = [UIColor colorWithRed: 0.282 green: 0.298 blue: 0.333 alpha: 1];
    UIColor* selectedButtonColor = [UIColor colorWithRed: 0.275 green: 0.396 blue: 0.843 alpha: 1];

    //// Variable Declarations
    UIColor* expression = speakerIsSelected ? selectedButtonColor : unSelectedButtonColor;


    //// Subframes
    CGRect innerFrame = CGRectMake(CGRectGetMinX(speakerFrame) + floor(CGRectGetWidth(speakerFrame) * 0.34359 + 0.5), CGRectGetMinY(speakerFrame) + floor(CGRectGetHeight(speakerFrame) * 0.17722 + 0.5), floor(CGRectGetWidth(speakerFrame) * 0.66154 + 0.5) - floor(CGRectGetWidth(speakerFrame) * 0.34359 + 0.5), floor(CGRectGetHeight(speakerFrame) * 0.81013 + 0.5) - floor(CGRectGetHeight(speakerFrame) * 0.17722 + 0.5));
    CGRect speakerGroup = CGRectMake(CGRectGetMinX(innerFrame) + 1.75, CGRectGetMinY(innerFrame) + floor(CGRectGetHeight(innerFrame) * 0.05000 + 0.5), floor((CGRectGetWidth(innerFrame) - 1.75) * 0.99419 + 1.6) - 1.1, floor(CGRectGetHeight(innerFrame) * 1.00000) - floor(CGRectGetHeight(innerFrame) * 0.05000 + 0.5) + 0.5);


    //// SpeakerOutline Drawing
    UIBezierPath* speakerOutlinePath = UIBezierPath.bezierPath;
    [speakerOutlinePath moveToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 6.59, CGRectGetMinY(speakerFrame) + 2)];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 6.59, CGRectGetMinY(speakerFrame) + 2)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 4.01, CGRectGetMinY(speakerFrame) + 2.2) controlPoint1: CGPointMake(CGRectGetMaxX(speakerFrame) - 5.27, CGRectGetMinY(speakerFrame) + 2) controlPoint2: CGPointMake(CGRectGetMaxX(speakerFrame) - 4.61, CGRectGetMinY(speakerFrame) + 2)];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 3.89, CGRectGetMinY(speakerFrame) + 2.23)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 2.22, CGRectGetMinY(speakerFrame) + 3.9) controlPoint1: CGPointMake(CGRectGetMaxX(speakerFrame) - 3.12, CGRectGetMinY(speakerFrame) + 2.51) controlPoint2: CGPointMake(CGRectGetMaxX(speakerFrame) - 2.51, CGRectGetMinY(speakerFrame) + 3.12)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 2, CGRectGetMinY(speakerFrame) + 6.61) controlPoint1: CGPointMake(CGRectGetMaxX(speakerFrame) - 2, CGRectGetMinY(speakerFrame) + 4.62) controlPoint2: CGPointMake(CGRectGetMaxX(speakerFrame) - 2, CGRectGetMinY(speakerFrame) + 5.28)];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 2, CGRectGetMaxY(speakerFrame) - 6.61)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 2.2, CGRectGetMaxY(speakerFrame) - 4.02) controlPoint1: CGPointMake(CGRectGetMaxX(speakerFrame) - 2, CGRectGetMaxY(speakerFrame) - 5.28) controlPoint2: CGPointMake(CGRectGetMaxX(speakerFrame) - 2, CGRectGetMaxY(speakerFrame) - 4.62)];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 2.22, CGRectGetMaxY(speakerFrame) - 3.9)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 3.89, CGRectGetMaxY(speakerFrame) - 2.23) controlPoint1: CGPointMake(CGRectGetMaxX(speakerFrame) - 2.51, CGRectGetMaxY(speakerFrame) - 3.12) controlPoint2: CGPointMake(CGRectGetMaxX(speakerFrame) - 3.12, CGRectGetMaxY(speakerFrame) - 2.51)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMaxX(speakerFrame) - 6.59, CGRectGetMaxY(speakerFrame) - 2) controlPoint1: CGPointMake(CGRectGetMaxX(speakerFrame) - 4.61, CGRectGetMaxY(speakerFrame) - 2) controlPoint2: CGPointMake(CGRectGetMaxX(speakerFrame) - 5.27, CGRectGetMaxY(speakerFrame) - 2)];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 6.59, CGRectGetMaxY(speakerFrame) - 2)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 4.01, CGRectGetMaxY(speakerFrame) - 2.2) controlPoint1: CGPointMake(CGRectGetMinX(speakerFrame) + 5.27, CGRectGetMaxY(speakerFrame) - 2) controlPoint2: CGPointMake(CGRectGetMinX(speakerFrame) + 4.61, CGRectGetMaxY(speakerFrame) - 2)];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 3.89, CGRectGetMaxY(speakerFrame) - 2.23)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 2.22, CGRectGetMaxY(speakerFrame) - 3.9) controlPoint1: CGPointMake(CGRectGetMinX(speakerFrame) + 3.12, CGRectGetMaxY(speakerFrame) - 2.51) controlPoint2: CGPointMake(CGRectGetMinX(speakerFrame) + 2.51, CGRectGetMaxY(speakerFrame) - 3.12)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 2, CGRectGetMaxY(speakerFrame) - 6.61) controlPoint1: CGPointMake(CGRectGetMinX(speakerFrame) + 2, CGRectGetMaxY(speakerFrame) - 4.62) controlPoint2: CGPointMake(CGRectGetMinX(speakerFrame) + 2, CGRectGetMaxY(speakerFrame) - 5.28)];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 2, CGRectGetMinY(speakerFrame) + 6.61)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 2.2, CGRectGetMinY(speakerFrame) + 4.02) controlPoint1: CGPointMake(CGRectGetMinX(speakerFrame) + 2, CGRectGetMinY(speakerFrame) + 5.28) controlPoint2: CGPointMake(CGRectGetMinX(speakerFrame) + 2, CGRectGetMinY(speakerFrame) + 4.62)];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 2.22, CGRectGetMinY(speakerFrame) + 3.9)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 3.89, CGRectGetMinY(speakerFrame) + 2.23) controlPoint1: CGPointMake(CGRectGetMinX(speakerFrame) + 2.51, CGRectGetMinY(speakerFrame) + 3.12) controlPoint2: CGPointMake(CGRectGetMinX(speakerFrame) + 3.12, CGRectGetMinY(speakerFrame) + 2.51)];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerFrame) + 6.59, CGRectGetMinY(speakerFrame) + 2) controlPoint1: CGPointMake(CGRectGetMinX(speakerFrame) + 4.61, CGRectGetMinY(speakerFrame) + 2) controlPoint2: CGPointMake(CGRectGetMinX(speakerFrame) + 5.27, CGRectGetMinY(speakerFrame) + 2)];
    [speakerOutlinePath closePath];
    [UIColor.lightGrayColor setStroke];
    speakerOutlinePath.lineWidth = 1;
    [speakerOutlinePath stroke];


    //// SpeakerGroup
    {
        //// SpeakerBezier Drawing
        UIBezierPath* speakerBezierPath = UIBezierPath.bezierPath;
        [speakerBezierPath moveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.09535 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.28606 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.57213 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.00000 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.57213 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 1.00000 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.28606 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.64789 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.09535 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.64789 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.52958 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.04156 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.64789 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.59718 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.41127 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.09535 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.34930 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.04401 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.09535 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath closePath];
        [speakerBezierPath moveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.87775 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.79155 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.60282 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.95110 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.71549 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.70704 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.90465 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47042 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.86797 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.65352 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.90465 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.56901 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.23380 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.90465 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.37183 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.86797 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.28732 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.87775 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.14930 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.95355 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.22817 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.34366 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath closePath];
        [speakerBezierPath moveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71149 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.64225 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.55211 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.76773 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.61972 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.66748 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.53239 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71638 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.69438 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.53239 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71638 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.50704 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.66748 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.41408 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71638 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.44225 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.69438 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.41408 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71149 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.30423 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.77017 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.32676 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.39437 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath closePath];
        speakerBezierPath.miterLimit = 4;

        [expression setFill];
        [speakerBezierPath fill];
    }
}

+ (void)drawTrashButtonWithOuterFrame: (CGRect)outerFrame speakerIsSelected: (BOOL)speakerIsSelected;
{
    //// Color Declarations
    UIColor* unSelectedButtonColor = [UIColor colorWithRed: 0.282 green: 0.298 blue: 0.333 alpha: 1];
    UIColor* selectedButtonColor = [UIColor colorWithRed: 0.275 green: 0.396 blue: 0.843 alpha: 1];

    //// Variable Declarations
    UIColor* expression = speakerIsSelected ? selectedButtonColor : unSelectedButtonColor;


    //// Subframes
    CGRect innerFrame = CGRectMake(CGRectGetMinX(outerFrame) + floor(CGRectGetWidth(outerFrame) * 0.27500 + 0.5), CGRectGetMinY(outerFrame) + floor(CGRectGetHeight(outerFrame) * 0.20000 + 0.5), floor(CGRectGetWidth(outerFrame) * 0.73750 + 0.5) - floor(CGRectGetWidth(outerFrame) * 0.27500 + 0.5), floor(CGRectGetHeight(outerFrame) * 0.78571 + 0.5) - floor(CGRectGetHeight(outerFrame) * 0.20000 + 0.5));
    CGRect group = CGRectMake(CGRectGetMinX(innerFrame) + 1, CGRectGetMinY(innerFrame) + 1, floor((CGRectGetWidth(innerFrame) - 1) * 0.97222 + 0.5), floor((CGRectGetHeight(innerFrame) - 1) * 0.97500 + 0.5));


    //// SpeakerOutline Drawing
    UIBezierPath* speakerOutlinePath = UIBezierPath.bezierPath;
    [speakerOutlinePath moveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.04405 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02500 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.95595 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02500 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.96887 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02747 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.96257 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02500 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.96588 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02500 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.96945 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02782 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.97782 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.04879 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.97334 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.03137 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.97640 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.03904 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.97895 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.08258 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.97895 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.05771 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.97895 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.06600 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.97895 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.90492 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.97796 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.93726 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.97895 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.92150 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.97895 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.92979 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.97782 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.93871 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.96945 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.95968 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.97640 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.94846 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.97334 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.95613 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.95595 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.96250 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.96588 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.96250 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.96257 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.96250 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.04405 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.96250 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.03113 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.96003 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.03743 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.96250 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.03412 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.96250 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.03055 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.95968 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.02218 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.93871 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.02666 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.95613 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.02360 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.94846 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.02105 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.90492 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.02105 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.92979 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.02105 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.92150 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.02105 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.08258 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.02204 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.05024 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.02105 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.06600 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.02105 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.05771 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addLineToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.02218 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.04879 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.03055 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02782 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.02360 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.03904 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.02666 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.03137 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath addCurveToPoint: CGPointMake(CGRectGetMinX(outerFrame) + 0.04405 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02500 * CGRectGetHeight(outerFrame)) controlPoint1: CGPointMake(CGRectGetMinX(outerFrame) + 0.03412 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02500 * CGRectGetHeight(outerFrame)) controlPoint2: CGPointMake(CGRectGetMinX(outerFrame) + 0.03743 * CGRectGetWidth(outerFrame), CGRectGetMinY(outerFrame) + 0.02500 * CGRectGetHeight(outerFrame))];
    [speakerOutlinePath closePath];
    [UIColor.lightGrayColor setStroke];
    speakerOutlinePath.lineWidth = 1;
    [speakerOutlinePath stroke];


    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.89394 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.10606 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.06667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30750 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.08485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.06667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.29000 * CGRectGetHeight(group))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.96500 * CGRectGetHeight(group))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16061 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98250 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.13788 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.83333 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.87273 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.96500 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.85455 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87273 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98250 * CGRectGetHeight(group))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.93485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30875 * CGRectGetHeight(group))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.89394 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.93182 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.29125 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.91515 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group))];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [expression setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.96667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.97121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.73636 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09250 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.97121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.88788 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.67879 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.31515 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.26364 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09750 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.04242 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11375 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.13182 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10500 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.05606 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11125 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.03636 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11250 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14250 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.01515 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11250 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12500 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15875 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.03485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17625 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.01364 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.96667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15875 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.98788 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17625 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14250 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.96667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12500 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.98788 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [expression setFill];
        [bezier2Path fill];
    }
}

+ (void)drawComposeIconWithFrame: (CGRect)frame;
{

    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 22.3, CGRectGetMinY(frame) + 30.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 34.3, CGRectGetMinY(frame) + 24.6) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 24.9, CGRectGetMinY(frame) + 26.9) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 29.6, CGRectGetMinY(frame) + 24.4)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 68.7, CGRectGetMinY(frame) + 24.6) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 45.7, CGRectGetMinY(frame) + 24.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 57.2, CGRectGetMinY(frame) + 24.6)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 59.4, CGRectGetMinY(frame) + 33.9) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 65.6, CGRectGetMinY(frame) + 27.7) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 62.5, CGRectGetMinY(frame) + 30.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 58.7, CGRectGetMinY(frame) + 34) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 59.2, CGRectGetMinY(frame) + 34.1) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 58.9, CGRectGetMinY(frame) + 34)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 34.6, CGRectGetMinY(frame) + 34) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 50.7, CGRectGetMinY(frame) + 34) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 42.6, CGRectGetMinY(frame) + 34)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 32.1, CGRectGetMinY(frame) + 34.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 33.7, CGRectGetMinY(frame) + 34) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 32.8, CGRectGetMinY(frame) + 34.1)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 38.9) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 30.5, CGRectGetMinY(frame) + 35.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 37)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 86.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 54.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 70.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 34, CGRectGetMinY(frame) + 90.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 88.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 31.6, CGRectGetMinY(frame) + 90.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 81.4, CGRectGetMinY(frame) + 90.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 49.8, CGRectGetMinY(frame) + 90.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 65.6, CGRectGetMinY(frame) + 90.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 86.2) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 83.8, CGRectGetMinY(frame) + 90.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 88.6)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 61.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 77.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 69.5)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 86.4, CGRectGetMinY(frame) + 60.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 85.9, CGRectGetMinY(frame) + 60.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 86.2, CGRectGetMinY(frame) + 60.6)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 51.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 89.4, CGRectGetMinY(frame) + 57.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 92.4, CGRectGetMinY(frame) + 54.5)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 83.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 62.2) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 72.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 95.1, CGRectGetMinY(frame) + 89) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 85.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 95.5, CGRectGetMinY(frame) + 87.2)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 89.6, CGRectGetMinY(frame) + 97.6) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 94.4, CGRectGetMinY(frame) + 92.4) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 92.4, CGRectGetMinY(frame) + 95.6)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 81.2, CGRectGetMinY(frame) + 100.3) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 87.2, CGRectGetMinY(frame) + 99.4) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 84.2, CGRectGetMinY(frame) + 100.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 34.9, CGRectGetMinY(frame) + 100.3) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 65.8, CGRectGetMinY(frame) + 100.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 50.4, CGRectGetMinY(frame) + 100.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 31.6, CGRectGetMinY(frame) + 100.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 33.8, CGRectGetMinY(frame) + 100.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 32.7, CGRectGetMinY(frame) + 100.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 22.8, CGRectGetMinY(frame) + 94.7) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 28.1, CGRectGetMinY(frame) + 99.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 24.9, CGRectGetMinY(frame) + 97.5)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 86) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 20.9, CGRectGetMinY(frame) + 92) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 89)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 38.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 70.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 54.5)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 22.3, CGRectGetMinY(frame) + 30.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 19.8, CGRectGetMinY(frame) + 36) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 20.7, CGRectGetMinY(frame) + 33.1)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 22.3, CGRectGetMinY(frame) + 30.8)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 83.9, CGRectGetMinY(frame) + 22.7)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 92.1, CGRectGetMinY(frame) + 20.2) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 20.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 89.1, CGRectGetMinY(frame) + 19.7)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 98.2, CGRectGetMinY(frame) + 24.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 94.6, CGRectGetMinY(frame) + 20.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 96.8, CGRectGetMinY(frame) + 22.1)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 98.6, CGRectGetMinY(frame) + 34.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 100.2, CGRectGetMinY(frame) + 27) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 100.4, CGRectGetMinY(frame) + 31)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 95.6, CGRectGetMinY(frame) + 37.6) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 97.9, CGRectGetMinY(frame) + 35.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 96.6, CGRectGetMinY(frame) + 36.5)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 90.1, CGRectGetMinY(frame) + 43.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 93.8, CGRectGetMinY(frame) + 39.4) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 91.9, CGRectGetMinY(frame) + 41.3)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 76.6, CGRectGetMinY(frame) + 30) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 85.6, CGRectGetMinY(frame) + 38.7) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 81.1, CGRectGetMinY(frame) + 34.3)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 83.9, CGRectGetMinY(frame) + 22.7) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 78.9, CGRectGetMinY(frame) + 27.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 81.4, CGRectGetMinY(frame) + 25.1)];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 83.9, CGRectGetMinY(frame) + 22.7)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];


        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
        [bezier3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 43.7, CGRectGetMinY(frame) + 62.8)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 72.4, CGRectGetMinY(frame) + 34.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 53.3, CGRectGetMinY(frame) + 53.2) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 62.8, CGRectGetMinY(frame) + 43.7)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 88.1, CGRectGetMinY(frame) + 45.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 76.9, CGRectGetMinY(frame) + 38.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 83.6, CGRectGetMinY(frame) + 40.7)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 57.7, CGRectGetMinY(frame) + 75.4) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 78.7, CGRectGetMinY(frame) + 54.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 67.1, CGRectGetMinY(frame) + 66.1)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 56.6, CGRectGetMinY(frame) + 76.3) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 57.3, CGRectGetMinY(frame) + 75.7) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 57.1, CGRectGetMinY(frame) + 76.2)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 38.4, CGRectGetMinY(frame) + 81.4) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 50.5, CGRectGetMinY(frame) + 78) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 44.5, CGRectGetMinY(frame) + 79.7)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 43.2, CGRectGetMinY(frame) + 63.7) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 40, CGRectGetMinY(frame) + 75.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 41.6, CGRectGetMinY(frame) + 69.6)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 43.7, CGRectGetMinY(frame) + 62.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 43.4, CGRectGetMinY(frame) + 63.4) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 43.4, CGRectGetMinY(frame) + 63)];
        [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 43.7, CGRectGetMinY(frame) + 62.8)];
        [bezier3Path closePath];
        bezier3Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier3Path fill];
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfSpeakerButtonWithSpeakerFrame: (CGRect)speakerFrame speakerIsSelected: (BOOL)speakerIsSelected;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(195, 80), NO, 0.0f);
    [JCStyleKit drawSpeakerButtonWithSpeakerFrame: speakerFrame speakerIsSelected: speakerIsSelected];
    UIImage* imageOfSpeakerButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfSpeakerButton;
}

+ (UIImage*)imageOfTrashButtonWithOuterFrame: (CGRect)outerFrame speakerIsSelected: (BOOL)speakerIsSelected;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(80, 70), NO, 0.0f);
    [JCStyleKit drawTrashButtonWithOuterFrame: outerFrame speakerIsSelected: speakerIsSelected];
    UIImage* imageOfTrashButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTrashButton;
}

@end
