//
//  JCStyleKit.m
//  JC
//
//  Created by Doug Leonard on 6/19/14.
//  Copyright (c) 2014 Jive. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "JCStyleKit.h"


@implementation JCStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawSpeakerButtonWithSpeakerFrame: (CGRect)speakerFrame speakerIsSelected: (BOOL)speakerIsSelected;
{
    //// Color Declarations
    UIColor* unSelectedButtonColor = [UIColor colorWithRed: 0.282 green: 0.298 blue: 0.333 alpha: 1];
    UIColor* selectedButtonColor = [UIColor colorWithRed: 0.275 green: 0.396 blue: 0.843 alpha: 1];

    //// Variable Declarations
    UIColor* expression = speakerIsSelected ? selectedButtonColor : unSelectedButtonColor;


    //// Subframes
    CGRect innerFrame = CGRectMake(CGRectGetMinX(speakerFrame) + floor(CGRectGetWidth(speakerFrame) * 0.37949 + 0.5), CGRectGetMinY(speakerFrame) + floor(CGRectGetHeight(speakerFrame) * 0.21429 + 0.5), floor(CGRectGetWidth(speakerFrame) * 0.62051 + 0.5) - floor(CGRectGetWidth(speakerFrame) * 0.37949 + 0.5), floor(CGRectGetHeight(speakerFrame) * 0.77143 + 0.5) - floor(CGRectGetHeight(speakerFrame) * 0.21429 + 0.5));
    CGRect speakerGroup = CGRectMake(CGRectGetMinX(innerFrame) + 0.75, CGRectGetMinY(innerFrame) + floor(CGRectGetHeight(innerFrame) * 0.02564) + 0.5, floor((CGRectGetWidth(innerFrame) - 0.75) * 0.99243 + 0.6) - 0.1, floor(CGRectGetHeight(innerFrame) * 0.98718 - 0.5) - floor(CGRectGetHeight(innerFrame) * 0.02564) + 0.5);


    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(CGRectGetMinX(speakerFrame) + 2, CGRectGetMinY(speakerFrame) + 2, floor((CGRectGetWidth(speakerFrame) - 2) * 0.98964 + 0.5), floor((CGRectGetHeight(speakerFrame) - 2) * 0.97059 + 0.5)) cornerRadius: 1];
    [expression setStroke];
    rectanglePath.lineWidth = 0.5;
    [rectanglePath stroke];


    //// SpeakerGroup
    {
        //// SpeakerBezier Drawing
        UIBezierPath* speakerBezierPath = UIBezierPath.bezierPath;
        [speakerBezierPath moveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.09535 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.28606 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.57213 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.00000 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.57213 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 1.00000 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.28606 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.64789 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.09535 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.64789 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.52958 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.04156 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.64789 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.59718 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.41127 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.09535 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.34930 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.04401 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.09535 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.29577 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath closePath];
        [speakerBezierPath moveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.87775 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.79155 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.60282 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.95110 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.71549 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.70704 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.90465 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47042 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.86797 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.65352 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.90465 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.56901 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.23380 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.90465 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.37183 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.86797 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.28732 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.87775 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.14930 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.95355 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.22817 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.34366 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 1.00000 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath closePath];
        [speakerBezierPath moveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71149 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.64225 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.55211 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.76773 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.61972 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.66748 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.53239 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71638 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.69438 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.53239 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71638 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.50704 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.66748 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.41408 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71638 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.44225 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.69438 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.41408 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.71149 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.30423 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup)) controlPoint1: CGPointMake(CGRectGetMinX(speakerGroup) + 0.77017 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.32676 * CGRectGetHeight(speakerGroup)) controlPoint2: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.39437 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath addLineToPoint: CGPointMake(CGRectGetMinX(speakerGroup) + 0.80929 * CGRectGetWidth(speakerGroup), CGRectGetMinY(speakerGroup) + 0.47324 * CGRectGetHeight(speakerGroup))];
        [speakerBezierPath closePath];
        speakerBezierPath.miterLimit = 4;

        [expression setFill];
        [speakerBezierPath fill];
    }
}

+ (void)drawTrashButtonWithOuterFrame: (CGRect)outerFrame selectWithDeleteColor: (BOOL)selectWithDeleteColor;
{
    //// Color Declarations
    UIColor* unSelectedButtonColor = [UIColor colorWithRed: 0.282 green: 0.298 blue: 0.333 alpha: 1];
    UIColor* deleteColor = [UIColor colorWithRed: 0.949 green: 0.302 blue: 0.216 alpha: 1];

    //// Variable Declarations
    UIColor* isSelectWithDeleteColor = selectWithDeleteColor ? deleteColor : unSelectedButtonColor;


    //// Subframes
    CGRect innerFrame = CGRectMake(CGRectGetMinX(outerFrame) + floor(CGRectGetWidth(outerFrame) * 0.29268 + 0.5), CGRectGetMinY(outerFrame) + floor(CGRectGetHeight(outerFrame) * 0.21429 + 0.5), floor(CGRectGetWidth(outerFrame) * 0.71951 + 0.5) - floor(CGRectGetWidth(outerFrame) * 0.29268 + 0.5), floor(CGRectGetHeight(outerFrame) * 0.77143 + 0.5) - floor(CGRectGetHeight(outerFrame) * 0.21429 + 0.5));
    CGRect group = CGRectMake(CGRectGetMinX(innerFrame) + 1, CGRectGetMinY(innerFrame) + 1, floor((CGRectGetWidth(innerFrame) - 1) * 0.97059 + 0.5), floor((CGRectGetHeight(innerFrame) - 1) * 0.97368 + 0.5));


    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(CGRectGetMinX(outerFrame) + 2, CGRectGetMinY(outerFrame) + 2, floor((CGRectGetWidth(outerFrame) - 2) * 0.97500 + 0.5), floor((CGRectGetHeight(outerFrame) - 2) * 0.97059 + 0.5)) cornerRadius: 1];
    [isSelectWithDeleteColor setStroke];
    rectanglePath.lineWidth = 0.5;
    [rectanglePath stroke];


    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.89394 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.10606 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.06667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30750 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.08485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.06667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.29000 * CGRectGetHeight(group))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.96500 * CGRectGetHeight(group))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16061 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98250 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.13788 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.83333 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.87273 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.96500 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.85455 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87273 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98250 * CGRectGetHeight(group))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.93485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30875 * CGRectGetHeight(group))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.89394 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.93182 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.29125 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.91515 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27500 * CGRectGetHeight(group))];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [isSelectWithDeleteColor setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.96667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.97121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.73636 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09250 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.97121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.88788 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.67879 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.31515 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.26364 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09750 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.04242 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11375 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.13182 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10500 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.05606 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11125 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.03636 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11250 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14250 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.01515 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11250 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12500 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15875 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.03485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17625 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.01364 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.96667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15875 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.98788 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17625 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14250 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.96667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12500 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.98788 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10000 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [isSelectWithDeleteColor setFill];
        [bezier2Path fill];
    }
}

+ (void)drawComposeIconWithFrame: (CGRect)frame;
{

    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 22.3, CGRectGetMinY(frame) + 30.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 34.3, CGRectGetMinY(frame) + 24.6) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 24.9, CGRectGetMinY(frame) + 26.9) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 29.6, CGRectGetMinY(frame) + 24.4)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 68.7, CGRectGetMinY(frame) + 24.6) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 45.7, CGRectGetMinY(frame) + 24.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 57.2, CGRectGetMinY(frame) + 24.6)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 59.4, CGRectGetMinY(frame) + 33.9) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 65.6, CGRectGetMinY(frame) + 27.7) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 62.5, CGRectGetMinY(frame) + 30.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 58.7, CGRectGetMinY(frame) + 34) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 59.2, CGRectGetMinY(frame) + 34.1) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 58.9, CGRectGetMinY(frame) + 34)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 34.6, CGRectGetMinY(frame) + 34) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 50.7, CGRectGetMinY(frame) + 34) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 42.6, CGRectGetMinY(frame) + 34)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 32.1, CGRectGetMinY(frame) + 34.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 33.7, CGRectGetMinY(frame) + 34) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 32.8, CGRectGetMinY(frame) + 34.1)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 38.9) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 30.5, CGRectGetMinY(frame) + 35.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 37)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 86.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 54.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 70.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 34, CGRectGetMinY(frame) + 90.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 29.4, CGRectGetMinY(frame) + 88.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 31.6, CGRectGetMinY(frame) + 90.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 81.4, CGRectGetMinY(frame) + 90.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 49.8, CGRectGetMinY(frame) + 90.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 65.6, CGRectGetMinY(frame) + 90.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 86.2) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 83.8, CGRectGetMinY(frame) + 90.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 88.6)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 61.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 77.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 69.5)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 86.4, CGRectGetMinY(frame) + 60.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 85.9, CGRectGetMinY(frame) + 60.8) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 86.2, CGRectGetMinY(frame) + 60.6)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 51.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 89.4, CGRectGetMinY(frame) + 57.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 92.4, CGRectGetMinY(frame) + 54.5)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 83.5) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 62.2) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 72.8)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 95.1, CGRectGetMinY(frame) + 89) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 95.4, CGRectGetMinY(frame) + 85.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 95.5, CGRectGetMinY(frame) + 87.2)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 89.6, CGRectGetMinY(frame) + 97.6) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 94.4, CGRectGetMinY(frame) + 92.4) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 92.4, CGRectGetMinY(frame) + 95.6)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 81.2, CGRectGetMinY(frame) + 100.3) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 87.2, CGRectGetMinY(frame) + 99.4) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 84.2, CGRectGetMinY(frame) + 100.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 34.9, CGRectGetMinY(frame) + 100.3) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 65.8, CGRectGetMinY(frame) + 100.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 50.4, CGRectGetMinY(frame) + 100.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 31.6, CGRectGetMinY(frame) + 100.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 33.8, CGRectGetMinY(frame) + 100.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 32.7, CGRectGetMinY(frame) + 100.3)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 22.8, CGRectGetMinY(frame) + 94.7) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 28.1, CGRectGetMinY(frame) + 99.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 24.9, CGRectGetMinY(frame) + 97.5)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 86) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 20.9, CGRectGetMinY(frame) + 92) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 89)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 38.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 70.3) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 19.9, CGRectGetMinY(frame) + 54.5)];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 22.3, CGRectGetMinY(frame) + 30.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 19.8, CGRectGetMinY(frame) + 36) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 20.7, CGRectGetMinY(frame) + 33.1)];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 22.3, CGRectGetMinY(frame) + 30.8)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 83.9, CGRectGetMinY(frame) + 22.7)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 92.1, CGRectGetMinY(frame) + 20.2) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 86, CGRectGetMinY(frame) + 20.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 89.1, CGRectGetMinY(frame) + 19.7)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 98.2, CGRectGetMinY(frame) + 24.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 94.6, CGRectGetMinY(frame) + 20.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 96.8, CGRectGetMinY(frame) + 22.1)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 98.6, CGRectGetMinY(frame) + 34.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 100.2, CGRectGetMinY(frame) + 27) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 100.4, CGRectGetMinY(frame) + 31)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 95.6, CGRectGetMinY(frame) + 37.6) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 97.9, CGRectGetMinY(frame) + 35.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 96.6, CGRectGetMinY(frame) + 36.5)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 90.1, CGRectGetMinY(frame) + 43.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 93.8, CGRectGetMinY(frame) + 39.4) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 91.9, CGRectGetMinY(frame) + 41.3)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 76.6, CGRectGetMinY(frame) + 30) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 85.6, CGRectGetMinY(frame) + 38.7) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 81.1, CGRectGetMinY(frame) + 34.3)];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 83.9, CGRectGetMinY(frame) + 22.7) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 78.9, CGRectGetMinY(frame) + 27.6) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 81.4, CGRectGetMinY(frame) + 25.1)];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 83.9, CGRectGetMinY(frame) + 22.7)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];


        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
        [bezier3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 43.7, CGRectGetMinY(frame) + 62.8)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 72.4, CGRectGetMinY(frame) + 34.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 53.3, CGRectGetMinY(frame) + 53.2) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 62.8, CGRectGetMinY(frame) + 43.7)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 88.1, CGRectGetMinY(frame) + 45.1) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 76.9, CGRectGetMinY(frame) + 38.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 83.6, CGRectGetMinY(frame) + 40.7)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 57.7, CGRectGetMinY(frame) + 75.4) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 78.7, CGRectGetMinY(frame) + 54.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 67.1, CGRectGetMinY(frame) + 66.1)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 56.6, CGRectGetMinY(frame) + 76.3) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 57.3, CGRectGetMinY(frame) + 75.7) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 57.1, CGRectGetMinY(frame) + 76.2)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 38.4, CGRectGetMinY(frame) + 81.4) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 50.5, CGRectGetMinY(frame) + 78) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 44.5, CGRectGetMinY(frame) + 79.7)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 43.2, CGRectGetMinY(frame) + 63.7) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 40, CGRectGetMinY(frame) + 75.5) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 41.6, CGRectGetMinY(frame) + 69.6)];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 43.7, CGRectGetMinY(frame) + 62.8) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 43.4, CGRectGetMinY(frame) + 63.4) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 43.4, CGRectGetMinY(frame) + 63)];
        [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 43.7, CGRectGetMinY(frame) + 62.8)];
        [bezier3Path closePath];
        bezier3Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier3Path fill];
    }
}

+ (void)drawPlay_PauseWithFrame: (CGRect)frame playPauseDisplaysPlay: (BOOL)playPauseDisplaysPlay;
{
    //// Color Declarations
    UIColor* unSelectedButtonColor = [UIColor colorWithRed: 0.282 green: 0.298 blue: 0.333 alpha: 1];

    //// Variable Declarations
    BOOL playPauseDisplaysPause = playPauseDisplaysPlay ? NO : YES;


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.31683 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.22321 - 0.5) + 1, floor(CGRectGetWidth(frame) * 0.84158 + 0.5) - floor(CGRectGetWidth(frame) * 0.31683 + 0.5), floor(CGRectGetHeight(frame) * 0.76786 - 0.5) - floor(CGRectGetHeight(frame) * 0.22321 - 0.5));


    if (playPauseDisplaysPlay)
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84011 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49769 * CGRectGetHeight(frame))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31928 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76873 * CGRectGetHeight(frame))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31928 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22664 * CGRectGetHeight(frame))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84011 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49769 * CGRectGetHeight(frame))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [unSelectedButtonColor setFill];
        [bezier2Path fill];
    }


    if (playPauseDisplaysPause)
    {
        //// Group
        {
            //// Rectangle Drawing
            UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(group) + floor(CGRectGetWidth(group) * 0.00000 + 0.5), CGRectGetMinY(group) + floor(CGRectGetHeight(group) * 0.00000 + 0.5), floor(CGRectGetWidth(group) * 0.41509 + 0.5) - floor(CGRectGetWidth(group) * 0.00000 + 0.5), floor(CGRectGetHeight(group) * 1.00000 + 0.5) - floor(CGRectGetHeight(group) * 0.00000 + 0.5))];
            [unSelectedButtonColor setFill];
            [rectanglePath fill];


            //// Rectangle 2 Drawing
            UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(group) + floor(CGRectGetWidth(group) * 0.58491 + 0.5), CGRectGetMinY(group) + floor(CGRectGetHeight(group) * 0.00000 + 0.5), floor(CGRectGetWidth(group) * 1.00000 + 0.5) - floor(CGRectGetWidth(group) * 0.58491 + 0.5), floor(CGRectGetHeight(group) * 1.00000 + 0.5) - floor(CGRectGetHeight(group) * 0.00000 + 0.5))];
            [unSelectedButtonColor setFill];
            [rectangle2Path fill];
        }
    }
}

+ (void)drawCanvas1;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(90, 57)];
    [bezierPath addLineToPoint: CGPointMake(55, 57)];
    [bezierPath addLineToPoint: CGPointMake(55, 22)];
    [bezierPath addLineToPoint: CGPointMake(46, 22)];
    [bezierPath addLineToPoint: CGPointMake(46, 57)];
    [bezierPath addLineToPoint: CGPointMake(10, 57)];
    [bezierPath addLineToPoint: CGPointMake(10, 66)];
    [bezierPath addLineToPoint: CGPointMake(46, 66)];
    [bezierPath addLineToPoint: CGPointMake(46, 102)];
    [bezierPath addLineToPoint: CGPointMake(55, 102)];
    [bezierPath addLineToPoint: CGPointMake(55, 66)];
    [bezierPath addLineToPoint: CGPointMake(90, 66)];
    [bezierPath addLineToPoint: CGPointMake(90, 57)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

+ (void)drawCanvas3;
{

    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(19.33, 18.68)];
        [bezierPath addCurveToPoint: CGPointMake(31.33, 12.48) controlPoint1: CGPointMake(21.93, 14.78) controlPoint2: CGPointMake(26.63, 12.28)];
        [bezierPath addCurveToPoint: CGPointMake(65.73, 12.48) controlPoint1: CGPointMake(42.73, 12.48) controlPoint2: CGPointMake(54.23, 12.48)];
        [bezierPath addCurveToPoint: CGPointMake(56.43, 21.78) controlPoint1: CGPointMake(62.63, 15.58) controlPoint2: CGPointMake(59.53, 18.68)];
        [bezierPath addCurveToPoint: CGPointMake(55.73, 21.88) controlPoint1: CGPointMake(56.23, 21.98) controlPoint2: CGPointMake(55.93, 21.88)];
        [bezierPath addCurveToPoint: CGPointMake(31.63, 21.88) controlPoint1: CGPointMake(47.73, 21.88) controlPoint2: CGPointMake(39.63, 21.88)];
        [bezierPath addCurveToPoint: CGPointMake(29.13, 22.38) controlPoint1: CGPointMake(30.73, 21.88) controlPoint2: CGPointMake(29.83, 21.98)];
        [bezierPath addCurveToPoint: CGPointMake(26.43, 26.78) controlPoint1: CGPointMake(27.53, 23.18) controlPoint2: CGPointMake(26.43, 24.88)];
        [bezierPath addCurveToPoint: CGPointMake(26.43, 73.98) controlPoint1: CGPointMake(26.43, 42.48) controlPoint2: CGPointMake(26.43, 58.18)];
        [bezierPath addCurveToPoint: CGPointMake(31.03, 78.68) controlPoint1: CGPointMake(26.43, 76.48) controlPoint2: CGPointMake(28.63, 78.68)];
        [bezierPath addCurveToPoint: CGPointMake(78.43, 78.68) controlPoint1: CGPointMake(46.83, 78.68) controlPoint2: CGPointMake(62.63, 78.68)];
        [bezierPath addCurveToPoint: CGPointMake(83.03, 74.08) controlPoint1: CGPointMake(80.83, 78.68) controlPoint2: CGPointMake(83.03, 76.48)];
        [bezierPath addCurveToPoint: CGPointMake(83.03, 48.98) controlPoint1: CGPointMake(83.03, 65.68) controlPoint2: CGPointMake(83.03, 57.38)];
        [bezierPath addCurveToPoint: CGPointMake(83.43, 48.38) controlPoint1: CGPointMake(82.93, 48.68) controlPoint2: CGPointMake(83.23, 48.48)];
        [bezierPath addCurveToPoint: CGPointMake(92.43, 39.38) controlPoint1: CGPointMake(86.43, 45.38) controlPoint2: CGPointMake(89.43, 42.38)];
        [bezierPath addCurveToPoint: CGPointMake(92.43, 71.38) controlPoint1: CGPointMake(92.43, 50.08) controlPoint2: CGPointMake(92.43, 60.68)];
        [bezierPath addCurveToPoint: CGPointMake(92.13, 76.88) controlPoint1: CGPointMake(92.43, 73.18) controlPoint2: CGPointMake(92.53, 75.08)];
        [bezierPath addCurveToPoint: CGPointMake(86.63, 85.48) controlPoint1: CGPointMake(91.43, 80.28) controlPoint2: CGPointMake(89.43, 83.48)];
        [bezierPath addCurveToPoint: CGPointMake(78.23, 88.18) controlPoint1: CGPointMake(84.23, 87.28) controlPoint2: CGPointMake(81.23, 88.18)];
        [bezierPath addCurveToPoint: CGPointMake(31.93, 88.18) controlPoint1: CGPointMake(62.83, 88.18) controlPoint2: CGPointMake(47.43, 88.18)];
        [bezierPath addCurveToPoint: CGPointMake(28.63, 87.98) controlPoint1: CGPointMake(30.83, 88.18) controlPoint2: CGPointMake(29.73, 88.18)];
        [bezierPath addCurveToPoint: CGPointMake(19.83, 82.58) controlPoint1: CGPointMake(25.13, 87.38) controlPoint2: CGPointMake(21.93, 85.38)];
        [bezierPath addCurveToPoint: CGPointMake(16.93, 73.88) controlPoint1: CGPointMake(17.93, 79.88) controlPoint2: CGPointMake(16.93, 76.88)];
        [bezierPath addCurveToPoint: CGPointMake(16.93, 26.68) controlPoint1: CGPointMake(16.93, 58.18) controlPoint2: CGPointMake(16.93, 42.38)];
        [bezierPath addCurveToPoint: CGPointMake(19.33, 18.68) controlPoint1: CGPointMake(16.83, 23.88) controlPoint2: CGPointMake(17.73, 20.98)];
        [bezierPath addLineToPoint: CGPointMake(19.33, 18.68)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(80.93, 10.58)];
        [bezier2Path addCurveToPoint: CGPointMake(89.13, 8.08) controlPoint1: CGPointMake(83.03, 8.48) controlPoint2: CGPointMake(86.13, 7.58)];
        [bezier2Path addCurveToPoint: CGPointMake(95.23, 11.98) controlPoint1: CGPointMake(91.63, 8.48) controlPoint2: CGPointMake(93.83, 9.98)];
        [bezier2Path addCurveToPoint: CGPointMake(95.63, 21.98) controlPoint1: CGPointMake(97.23, 14.88) controlPoint2: CGPointMake(97.43, 18.88)];
        [bezier2Path addCurveToPoint: CGPointMake(92.63, 25.48) controlPoint1: CGPointMake(94.93, 23.38) controlPoint2: CGPointMake(93.63, 24.38)];
        [bezier2Path addCurveToPoint: CGPointMake(87.13, 30.98) controlPoint1: CGPointMake(90.83, 27.28) controlPoint2: CGPointMake(88.93, 29.18)];
        [bezier2Path addCurveToPoint: CGPointMake(73.63, 17.88) controlPoint1: CGPointMake(82.63, 26.58) controlPoint2: CGPointMake(78.13, 22.18)];
        [bezier2Path addCurveToPoint: CGPointMake(80.93, 10.58) controlPoint1: CGPointMake(75.93, 15.48) controlPoint2: CGPointMake(78.43, 12.98)];
        [bezier2Path addLineToPoint: CGPointMake(80.93, 10.58)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];


        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
        [bezier3Path moveToPoint: CGPointMake(40.73, 50.68)];
        [bezier3Path addCurveToPoint: CGPointMake(69.43, 21.98) controlPoint1: CGPointMake(50.33, 41.08) controlPoint2: CGPointMake(59.83, 31.58)];
        [bezier3Path addCurveToPoint: CGPointMake(85.13, 32.98) controlPoint1: CGPointMake(73.93, 26.38) controlPoint2: CGPointMake(80.63, 28.58)];
        [bezier3Path addCurveToPoint: CGPointMake(54.73, 63.28) controlPoint1: CGPointMake(75.73, 42.38) controlPoint2: CGPointMake(64.13, 53.98)];
        [bezier3Path addCurveToPoint: CGPointMake(53.63, 64.18) controlPoint1: CGPointMake(54.33, 63.58) controlPoint2: CGPointMake(54.13, 64.08)];
        [bezier3Path addCurveToPoint: CGPointMake(35.43, 69.28) controlPoint1: CGPointMake(47.53, 65.88) controlPoint2: CGPointMake(41.53, 67.58)];
        [bezier3Path addCurveToPoint: CGPointMake(40.23, 51.58) controlPoint1: CGPointMake(37.03, 63.38) controlPoint2: CGPointMake(38.63, 57.48)];
        [bezier3Path addCurveToPoint: CGPointMake(40.73, 50.68) controlPoint1: CGPointMake(40.43, 51.28) controlPoint2: CGPointMake(40.43, 50.88)];
        [bezier3Path addLineToPoint: CGPointMake(40.73, 50.68)];
        [bezier3Path closePath];
        bezier3Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier3Path fill];
    }
}

+ (void)drawCanvas5;
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color3 = [UIColor colorWithRed: 0.005 green: 0.005 blue: 0.005 alpha: 1];

    //// Group
    {
        //// Group 2
        {
            //// Group 3
            {

                //// Clip Bezier
                UIBezierPath* bezierPath = UIBezierPath.bezierPath;
                [bezierPath moveToPoint: CGPointMake(-121.1, 42.7)];
                [bezierPath addLineToPoint: CGPointMake(-105.9, 42.7)];
                [bezierPath addLineToPoint: CGPointMake(-83, 22.3)];
                [bezierPath addLineToPoint: CGPointMake(-83, 91.7)];
                [bezierPath addLineToPoint: CGPointMake(-105.9, 67.1)];
                [bezierPath addLineToPoint: CGPointMake(-121.1, 67.1)];
                [bezierPath addCurveToPoint: CGPointMake(-128.7, 58.9) controlPoint1: CGPointMake(-125.3, 67.1) controlPoint2: CGPointMake(-128.7, 63.4)];
                [bezierPath addLineToPoint: CGPointMake(-128.7, 50.7)];
                [bezierPath addCurveToPoint: CGPointMake(-121.1, 42.7) controlPoint1: CGPointMake(-128.7, 46.3) controlPoint2: CGPointMake(-125.3, 42.7)];
                [bezierPath addLineToPoint: CGPointMake(-121.1, 42.7)];
                [bezierPath closePath];
                [bezierPath moveToPoint: CGPointMake(-48.7, 54.9)];
                [bezierPath addCurveToPoint: CGPointMake(-58.5, 77) controlPoint1: CGPointMake(-48.7, 63.8) controlPoint2: CGPointMake(-52.5, 71.8)];
                [bezierPath addLineToPoint: CGPointMake(-63.9, 71.2)];
                [bezierPath addCurveToPoint: CGPointMake(-56.3, 54.9) controlPoint1: CGPointMake(-59.3, 67.5) controlPoint2: CGPointMake(-56.3, 61.5)];
                [bezierPath addCurveToPoint: CGPointMake(-63.9, 38.6) controlPoint1: CGPointMake(-56.3, 48.2) controlPoint2: CGPointMake(-59.3, 42.3)];
                [bezierPath addLineToPoint: CGPointMake(-58.5, 32.8)];
                [bezierPath addCurveToPoint: CGPointMake(-48.7, 54.9) controlPoint1: CGPointMake(-52.6, 38) controlPoint2: CGPointMake(-48.7, 46)];
                [bezierPath addLineToPoint: CGPointMake(-48.7, 54.9)];
                [bezierPath closePath];
                [bezierPath moveToPoint: CGPointMake(-64, 54.9)];
                [bezierPath addCurveToPoint: CGPointMake(-71.9, 66.5) controlPoint1: CGPointMake(-64, 60.3) controlPoint2: CGPointMake(-67.3, 65)];
                [bezierPath addLineToPoint: CGPointMake(-75.4, 58.9)];
                [bezierPath addCurveToPoint: CGPointMake(-71.6, 54.8) controlPoint1: CGPointMake(-73.3, 58.9) controlPoint2: CGPointMake(-71.6, 57.1)];
                [bezierPath addCurveToPoint: CGPointMake(-75.4, 50.7) controlPoint1: CGPointMake(-71.6, 52.5) controlPoint2: CGPointMake(-73.3, 50.7)];
                [bezierPath addLineToPoint: CGPointMake(-71.9, 43.1)];
                [bezierPath addCurveToPoint: CGPointMake(-64, 54.9) controlPoint1: CGPointMake(-67.3, 44.8) controlPoint2: CGPointMake(-64, 49.5)];
                [bezierPath addLineToPoint: CGPointMake(-64, 54.9)];
                [bezierPath closePath];
                [bezierPath addClip];
            }
        }
    }


    //// Group 4
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(28.1, 47.9)];
        [bezier2Path addLineToPoint: CGPointMake(28.1, 84.3)];
        [bezier2Path addLineToPoint: CGPointMake(108.1, 84.3)];
        [bezier2Path addLineToPoint: CGPointMake(108.1, 47.9)];
        [bezier2Path addLineToPoint: CGPointMake(68.1, 66.5)];
        [bezier2Path addLineToPoint: CGPointMake(28.1, 47.9)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [color3 setFill];
        [bezier2Path fill];


        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
        [bezier3Path moveToPoint: CGPointMake(28.1, 30.3)];
        [bezier3Path addLineToPoint: CGPointMake(28.1, 41.5)];
        [bezier3Path addLineToPoint: CGPointMake(68.1, 59.1)];
        [bezier3Path addLineToPoint: CGPointMake(108.1, 41.5)];
        [bezier3Path addLineToPoint: CGPointMake(108.1, 30.3)];
        [bezier3Path addLineToPoint: CGPointMake(28.1, 30.3)];
        [bezier3Path closePath];
        bezier3Path.miterLimit = 4;

        [color3 setFill];
        [bezier3Path fill];
    }
}

+ (void)drawCanvas2;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(29.8, 55.5)];
    [bezierPath addLineToPoint: CGPointMake(30.8, 54.5)];
    [bezierPath addLineToPoint: CGPointMake(41.1, 44.3)];
    [bezierPath addLineToPoint: CGPointMake(68.7, 17)];
    [bezierPath addLineToPoint: CGPointMake(52, 15.7)];
    [bezierPath addLineToPoint: CGPointMake(23.1, 44.3)];
    [bezierPath addLineToPoint: CGPointMake(12.8, 54.5)];
    [bezierPath addLineToPoint: CGPointMake(11.8, 55.5)];
    [bezierPath addLineToPoint: CGPointMake(51.5, 95.7)];
    [bezierPath addLineToPoint: CGPointMake(68.4, 94.5)];
    [bezierPath addLineToPoint: CGPointMake(29.8, 55.5)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

+ (void)drawCanvas4;
{
    //// Color Declarations
    UIColor* color2 = [UIColor colorWithRed: 0.151 green: 0.151 blue: 0.151 alpha: 1];

    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(94.5, 80.7)];
        [bezierPath addCurveToPoint: CGPointMake(91.2, 84) controlPoint1: CGPointMake(94.5, 82.5) controlPoint2: CGPointMake(93, 84)];
        [bezierPath addLineToPoint: CGPointMake(85.8, 84)];
        [bezierPath addCurveToPoint: CGPointMake(82.5, 80.7) controlPoint1: CGPointMake(84, 84) controlPoint2: CGPointMake(82.5, 82.5)];
        [bezierPath addLineToPoint: CGPointMake(82.5, 70.3)];
        [bezierPath addCurveToPoint: CGPointMake(85.8, 67) controlPoint1: CGPointMake(82.5, 68.5) controlPoint2: CGPointMake(84, 67)];
        [bezierPath addLineToPoint: CGPointMake(91.2, 67)];
        [bezierPath addCurveToPoint: CGPointMake(94.5, 70.3) controlPoint1: CGPointMake(93, 67) controlPoint2: CGPointMake(94.5, 68.5)];
        [bezierPath addLineToPoint: CGPointMake(94.5, 80.7)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [color2 setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(94.5, 59.7)];
        [bezier2Path addCurveToPoint: CGPointMake(91.2, 63) controlPoint1: CGPointMake(94.5, 61.5) controlPoint2: CGPointMake(93, 63)];
        [bezier2Path addLineToPoint: CGPointMake(85.8, 63)];
        [bezier2Path addCurveToPoint: CGPointMake(82.5, 59.7) controlPoint1: CGPointMake(84, 63) controlPoint2: CGPointMake(82.5, 61.5)];
        [bezier2Path addLineToPoint: CGPointMake(82.5, 49.3)];
        [bezier2Path addCurveToPoint: CGPointMake(85.8, 46) controlPoint1: CGPointMake(82.5, 47.5) controlPoint2: CGPointMake(84, 46)];
        [bezier2Path addLineToPoint: CGPointMake(91.2, 46)];
        [bezier2Path addCurveToPoint: CGPointMake(94.5, 49.3) controlPoint1: CGPointMake(93, 46) controlPoint2: CGPointMake(94.5, 47.5)];
        [bezier2Path addLineToPoint: CGPointMake(94.5, 59.7)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [color2 setFill];
        [bezier2Path fill];


        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
        [bezier3Path moveToPoint: CGPointMake(94.5, 36.7)];
        [bezier3Path addCurveToPoint: CGPointMake(91.2, 40) controlPoint1: CGPointMake(94.5, 38.5) controlPoint2: CGPointMake(93, 40)];
        [bezier3Path addLineToPoint: CGPointMake(85.8, 40)];
        [bezier3Path addCurveToPoint: CGPointMake(82.5, 36.7) controlPoint1: CGPointMake(84, 40) controlPoint2: CGPointMake(82.5, 38.5)];
        [bezier3Path addLineToPoint: CGPointMake(82.5, 26.3)];
        [bezier3Path addCurveToPoint: CGPointMake(85.8, 23) controlPoint1: CGPointMake(82.5, 24.5) controlPoint2: CGPointMake(84, 23)];
        [bezier3Path addLineToPoint: CGPointMake(91.2, 23)];
        [bezier3Path addCurveToPoint: CGPointMake(94.5, 26.3) controlPoint1: CGPointMake(93, 23) controlPoint2: CGPointMake(94.5, 24.5)];
        [bezier3Path addLineToPoint: CGPointMake(94.5, 36.7)];
        [bezier3Path closePath];
        bezier3Path.miterLimit = 4;

        [color2 setFill];
        [bezier3Path fill];


        //// Bezier 4 Drawing
        UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
        [bezier4Path moveToPoint: CGPointMake(84.9, 14)];
        [bezier4Path addLineToPoint: CGPointMake(18.8, 14)];
        [bezier4Path addCurveToPoint: CGPointMake(15.5, 17.7) controlPoint1: CGPointMake(16.9, 14) controlPoint2: CGPointMake(15.5, 15.9)];
        [bezier4Path addLineToPoint: CGPointMake(15.5, 91.1)];
        [bezier4Path addCurveToPoint: CGPointMake(19.8, 94) controlPoint1: CGPointMake(15.5, 92.9) controlPoint2: CGPointMake(16.9, 94)];
        [bezier4Path addLineToPoint: CGPointMake(86, 94)];
        [bezier4Path addCurveToPoint: CGPointMake(88.5, 91.1) controlPoint1: CGPointMake(86.8, 94) controlPoint2: CGPointMake(88.5, 92.9)];
        [bezier4Path addLineToPoint: CGPointMake(88.5, 17.7)];
        [bezier4Path addCurveToPoint: CGPointMake(84.9, 14) controlPoint1: CGPointMake(88.5, 15.9) controlPoint2: CGPointMake(86.8, 14)];
        [bezier4Path closePath];
        [bezier4Path moveToPoint: CGPointMake(72.8, 69.5)];
        [bezier4Path addCurveToPoint: CGPointMake(70.6, 71.7) controlPoint1: CGPointMake(72.4, 70.5) controlPoint2: CGPointMake(71.5, 71.2)];
        [bezier4Path addCurveToPoint: CGPointMake(65.7, 73.2) controlPoint1: CGPointMake(69.1, 72.5) controlPoint2: CGPointMake(67.4, 72.9)];
        [bezier4Path addCurveToPoint: CGPointMake(56.4, 73.8) controlPoint1: CGPointMake(62.6, 73.7) controlPoint2: CGPointMake(59.5, 73.8)];
        [bezier4Path addCurveToPoint: CGPointMake(48.5, 73.3) controlPoint1: CGPointMake(53.7, 73.8) controlPoint2: CGPointMake(51.1, 73.7)];
        [bezier4Path addCurveToPoint: CGPointMake(43.4, 72) controlPoint1: CGPointMake(46.8, 73.1) controlPoint2: CGPointMake(45, 72.7)];
        [bezier4Path addCurveToPoint: CGPointMake(40.8, 70.2) controlPoint1: CGPointMake(42.4, 71.6) controlPoint2: CGPointMake(41.5, 71)];
        [bezier4Path addCurveToPoint: CGPointMake(40.2, 68.2) controlPoint1: CGPointMake(40.4, 69.6) controlPoint2: CGPointMake(40.1, 68.9)];
        [bezier4Path addCurveToPoint: CGPointMake(40.3, 66.3) controlPoint1: CGPointMake(40.2, 67.6) controlPoint2: CGPointMake(40.1, 66.9)];
        [bezier4Path addCurveToPoint: CGPointMake(41.5, 64.4) controlPoint1: CGPointMake(40.5, 65.6) controlPoint2: CGPointMake(41, 64.9)];
        [bezier4Path addCurveToPoint: CGPointMake(44.7, 61.9) controlPoint1: CGPointMake(42.4, 63.4) controlPoint2: CGPointMake(43.5, 62.6)];
        [bezier4Path addCurveToPoint: CGPointMake(50.6, 59.1) controlPoint1: CGPointMake(46.6, 60.8) controlPoint2: CGPointMake(48.5, 59.8)];
        [bezier4Path addCurveToPoint: CGPointMake(51.3, 58.8) controlPoint1: CGPointMake(50.8, 59) controlPoint2: CGPointMake(51.1, 58.9)];
        [bezier4Path addCurveToPoint: CGPointMake(52.2, 54.5) controlPoint1: CGPointMake(52.4, 57.7) controlPoint2: CGPointMake(52.8, 55.9)];
        [bezier4Path addCurveToPoint: CGPointMake(48.1, 46.6) controlPoint1: CGPointMake(50.1, 52.3) controlPoint2: CGPointMake(48.7, 49.5)];
        [bezier4Path addCurveToPoint: CGPointMake(48.6, 39.9) controlPoint1: CGPointMake(47.7, 44.4) controlPoint2: CGPointMake(47.7, 42)];
        [bezier4Path addCurveToPoint: CGPointMake(51.7, 36.1) controlPoint1: CGPointMake(49.2, 38.4) controlPoint2: CGPointMake(50.3, 37)];
        [bezier4Path addCurveToPoint: CGPointMake(55.5, 34.7) controlPoint1: CGPointMake(52.8, 35.3) controlPoint2: CGPointMake(54.2, 34.9)];
        [bezier4Path addCurveToPoint: CGPointMake(61.9, 36.1) controlPoint1: CGPointMake(57.7, 34.4) controlPoint2: CGPointMake(60, 34.9)];
        [bezier4Path addCurveToPoint: CGPointMake(65.1, 39.9) controlPoint1: CGPointMake(63.3, 37) controlPoint2: CGPointMake(64.4, 38.4)];
        [bezier4Path addCurveToPoint: CGPointMake(65.7, 46) controlPoint1: CGPointMake(65.9, 41.8) controlPoint2: CGPointMake(66, 44)];
        [bezier4Path addCurveToPoint: CGPointMake(61.4, 54.5) controlPoint1: CGPointMake(65.1, 49.2) controlPoint2: CGPointMake(63.6, 52.1)];
        [bezier4Path addCurveToPoint: CGPointMake(61.2, 55.2) controlPoint1: CGPointMake(61.2, 54.7) controlPoint2: CGPointMake(61.2, 55)];
        [bezier4Path addCurveToPoint: CGPointMake(61.6, 58.4) controlPoint1: CGPointMake(61, 56.3) controlPoint2: CGPointMake(61, 57.4)];
        [bezier4Path addCurveToPoint: CGPointMake(62.3, 59.1) controlPoint1: CGPointMake(61.8, 58.7) controlPoint2: CGPointMake(62, 59)];
        [bezier4Path addCurveToPoint: CGPointMake(68.4, 61.8) controlPoint1: CGPointMake(64.4, 59.8) controlPoint2: CGPointMake(66.5, 60.7)];
        [bezier4Path addCurveToPoint: CGPointMake(72.1, 64.7) controlPoint1: CGPointMake(69.7, 62.6) controlPoint2: CGPointMake(71.1, 63.5)];
        [bezier4Path addCurveToPoint: CGPointMake(73.3, 67.5) controlPoint1: CGPointMake(72.8, 65.5) controlPoint2: CGPointMake(73.3, 66.4)];
        [bezier4Path addCurveToPoint: CGPointMake(72.8, 69.5) controlPoint1: CGPointMake(73, 67.9) controlPoint2: CGPointMake(73.1, 68.7)];
        [bezier4Path closePath];
        bezier4Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier4Path fill];


        //// Bezier 5 Drawing
        UIBezierPath* bezier5Path = UIBezierPath.bezierPath;
        [bezier5Path moveToPoint: CGPointMake(26.5, 90.7)];
        [bezier5Path addCurveToPoint: CGPointMake(23.2, 94) controlPoint1: CGPointMake(26.5, 92.5) controlPoint2: CGPointMake(25, 94)];
        [bezier5Path addLineToPoint: CGPointMake(18.8, 94)];
        [bezier5Path addCurveToPoint: CGPointMake(15.5, 90.7) controlPoint1: CGPointMake(17, 94) controlPoint2: CGPointMake(15.5, 92.5)];
        [bezier5Path addLineToPoint: CGPointMake(15.5, 17.3)];
        [bezier5Path addCurveToPoint: CGPointMake(18.8, 14) controlPoint1: CGPointMake(15.5, 15.5) controlPoint2: CGPointMake(17, 14)];
        [bezier5Path addLineToPoint: CGPointMake(23.2, 14)];
        [bezier5Path addCurveToPoint: CGPointMake(26.5, 17.3) controlPoint1: CGPointMake(25, 14) controlPoint2: CGPointMake(26.5, 15.5)];
        [bezier5Path addLineToPoint: CGPointMake(26.5, 90.7)];
        [bezier5Path closePath];
        bezier5Path.miterLimit = 4;

        [color2 setFill];
        [bezier5Path fill];
    }
}

+ (void)drawCanvas6;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(39.3, 16)];
    [bezierPath addCurveToPoint: CGPointMake(13, 42.2) controlPoint1: CGPointMake(24.8, 16) controlPoint2: CGPointMake(13, 27.8)];
    [bezierPath addCurveToPoint: CGPointMake(37.8, 94.5) controlPoint1: CGPointMake(13, 56.1) controlPoint2: CGPointMake(36.8, 93.1)];
    [bezierPath addLineToPoint: CGPointMake(38.7, 95.8)];
    [bezierPath addCurveToPoint: CGPointMake(39.2, 96) controlPoint1: CGPointMake(38.8, 96) controlPoint2: CGPointMake(39, 96)];
    [bezierPath addCurveToPoint: CGPointMake(39.7, 95.8) controlPoint1: CGPointMake(39.4, 96) controlPoint2: CGPointMake(39.6, 95.9)];
    [bezierPath addLineToPoint: CGPointMake(40.6, 94.5)];
    [bezierPath addCurveToPoint: CGPointMake(65.4, 42.2) controlPoint1: CGPointMake(41.6, 93.1) controlPoint2: CGPointMake(65.4, 56.2)];
    [bezierPath addCurveToPoint: CGPointMake(39.3, 16) controlPoint1: CGPointMake(65.5, 27.8) controlPoint2: CGPointMake(53.7, 16)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(39.3, 32.8)];
    [bezierPath addCurveToPoint: CGPointMake(48.7, 42.2) controlPoint1: CGPointMake(44.5, 32.8) controlPoint2: CGPointMake(48.7, 37)];
    [bezierPath addCurveToPoint: CGPointMake(39.3, 51.6) controlPoint1: CGPointMake(48.7, 47.4) controlPoint2: CGPointMake(44.5, 51.6)];
    [bezierPath addCurveToPoint: CGPointMake(29.9, 42.2) controlPoint1: CGPointMake(34.1, 51.6) controlPoint2: CGPointMake(29.9, 47.4)];
    [bezierPath addCurveToPoint: CGPointMake(39.3, 32.8) controlPoint1: CGPointMake(29.9, 37) controlPoint2: CGPointMake(34.1, 32.8)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

+ (void)drawCanvas7;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(91, 73.43)];
    [bezierPath addCurveToPoint: CGPointMake(82.6, 81.63) controlPoint1: CGPointMake(91, 77.93) controlPoint2: CGPointMake(87.2, 81.63)];
    [bezierPath addLineToPoint: CGPointMake(74.9, 81.63)];
    [bezierPath addLineToPoint: CGPointMake(51.8, 99.73)];
    [bezierPath addLineToPoint: CGPointMake(51.7, 81.23)];
    [bezierPath addLineToPoint: CGPointMake(19.9, 81.23)];
    [bezierPath addCurveToPoint: CGPointMake(11, 73.43) controlPoint1: CGPointMake(15.4, 81.23) controlPoint2: CGPointMake(11, 77.93)];
    [bezierPath addLineToPoint: CGPointMake(11, 32.23)];
    [bezierPath addCurveToPoint: CGPointMake(19.9, 24.23) controlPoint1: CGPointMake(11, 27.73) controlPoint2: CGPointMake(15.4, 24.23)];
    [bezierPath addLineToPoint: CGPointMake(82.5, 24.23)];
    [bezierPath addCurveToPoint: CGPointMake(91, 32.23) controlPoint1: CGPointMake(87, 24.23) controlPoint2: CGPointMake(91, 27.73)];
    [bezierPath addLineToPoint: CGPointMake(91, 73.43)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

+ (void)drawCanvas8;
{

    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(32.29, 75.79)];
        [bezierPath addCurveToPoint: CGPointMake(32.29, 90.07) controlPoint1: CGPointMake(36.24, 79.73) controlPoint2: CGPointMake(36.24, 86.13)];
        [bezierPath addCurveToPoint: CGPointMake(18.01, 90.07) controlPoint1: CGPointMake(28.35, 94.02) controlPoint2: CGPointMake(21.95, 94.02)];
        [bezierPath addCurveToPoint: CGPointMake(18.01, 75.79) controlPoint1: CGPointMake(14.06, 86.13) controlPoint2: CGPointMake(14.06, 79.73)];
        [bezierPath addCurveToPoint: CGPointMake(32.29, 75.79) controlPoint1: CGPointMake(21.95, 71.84) controlPoint2: CGPointMake(28.35, 71.84)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(62.09, 75.89)];
        [bezier2Path addCurveToPoint: CGPointMake(62.09, 90.17) controlPoint1: CGPointMake(66.04, 79.83) controlPoint2: CGPointMake(66.04, 86.23)];
        [bezier2Path addCurveToPoint: CGPointMake(47.81, 90.17) controlPoint1: CGPointMake(58.15, 94.12) controlPoint2: CGPointMake(51.75, 94.12)];
        [bezier2Path addCurveToPoint: CGPointMake(47.81, 75.89) controlPoint1: CGPointMake(43.86, 86.23) controlPoint2: CGPointMake(43.86, 79.83)];
        [bezier2Path addCurveToPoint: CGPointMake(62.09, 75.89) controlPoint1: CGPointMake(51.75, 71.94) controlPoint2: CGPointMake(58.15, 71.94)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];


        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
        [bezier3Path moveToPoint: CGPointMake(91.99, 75.79)];
        [bezier3Path addCurveToPoint: CGPointMake(91.99, 90.07) controlPoint1: CGPointMake(95.94, 79.73) controlPoint2: CGPointMake(95.94, 86.13)];
        [bezier3Path addCurveToPoint: CGPointMake(77.71, 90.07) controlPoint1: CGPointMake(88.05, 94.02) controlPoint2: CGPointMake(81.65, 94.02)];
        [bezier3Path addCurveToPoint: CGPointMake(77.71, 75.79) controlPoint1: CGPointMake(73.76, 86.13) controlPoint2: CGPointMake(73.76, 79.73)];
        [bezier3Path addCurveToPoint: CGPointMake(91.99, 75.79) controlPoint1: CGPointMake(81.65, 71.84) controlPoint2: CGPointMake(88.05, 71.84)];
        [bezier3Path closePath];
        bezier3Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier3Path fill];
    }
}

+ (void)drawCanvas9;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(98, 49.4)];
    [bezierPath addCurveToPoint: CGPointMake(78, 69.4) controlPoint1: CGPointMake(98, 60.4) controlPoint2: CGPointMake(89, 69.4)];
    [bezierPath addLineToPoint: CGPointMake(68.9, 69.4)];
    [bezierPath addLineToPoint: CGPointMake(57.8, 92.6)];
    [bezierPath addLineToPoint: CGPointMake(46.7, 69.4)];
    [bezierPath addLineToPoint: CGPointMake(38, 69.4)];
    [bezierPath addCurveToPoint: CGPointMake(18, 49.4) controlPoint1: CGPointMake(27, 69.4) controlPoint2: CGPointMake(18, 60.4)];
    [bezierPath addLineToPoint: CGPointMake(18, 49.4)];
    [bezierPath addCurveToPoint: CGPointMake(38, 29.4) controlPoint1: CGPointMake(18, 38.4) controlPoint2: CGPointMake(27, 29.4)];
    [bezierPath addLineToPoint: CGPointMake(78, 29.4)];
    [bezierPath addCurveToPoint: CGPointMake(98, 49.4) controlPoint1: CGPointMake(89, 29.4) controlPoint2: CGPointMake(98, 38.4)];
    [bezierPath addLineToPoint: CGPointMake(98, 49.4)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

+ (void)drawCanvas10;
{
    //// Color Declarations
    UIColor* color4 = [UIColor colorWithRed: 0.071 green: 0.071 blue: 0.071 alpha: 1];

    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(95, 85.8)];
        [bezierPath addCurveToPoint: CGPointMake(93.2, 90.1) controlPoint1: CGPointMake(95, 87.5) controlPoint2: CGPointMake(94.4, 88.9)];
        [bezierPath addCurveToPoint: CGPointMake(88.8, 92) controlPoint1: CGPointMake(92, 91.4) controlPoint2: CGPointMake(90.5, 92)];
        [bezierPath addCurveToPoint: CGPointMake(84.5, 90.2) controlPoint1: CGPointMake(87.1, 92) controlPoint2: CGPointMake(85.6, 91.4)];
        [bezierPath addLineToPoint: CGPointMake(68, 73.7)];
        [bezierPath addCurveToPoint: CGPointMake(48.8, 79.7) controlPoint1: CGPointMake(62.3, 77.7) controlPoint2: CGPointMake(55.9, 79.7)];
        [bezierPath addCurveToPoint: CGPointMake(35.7, 77) controlPoint1: CGPointMake(44.2, 79.7) controlPoint2: CGPointMake(39.8, 78.8)];
        [bezierPath addCurveToPoint: CGPointMake(24.9, 69.8) controlPoint1: CGPointMake(31.5, 75.2) controlPoint2: CGPointMake(27.9, 72.8)];
        [bezierPath addCurveToPoint: CGPointMake(17.7, 59) controlPoint1: CGPointMake(21.9, 66.8) controlPoint2: CGPointMake(19.5, 63.2)];
        [bezierPath addCurveToPoint: CGPointMake(15, 45.8) controlPoint1: CGPointMake(15.9, 54.8) controlPoint2: CGPointMake(15, 50.4)];
        [bezierPath addCurveToPoint: CGPointMake(17.7, 32.7) controlPoint1: CGPointMake(15, 41.2) controlPoint2: CGPointMake(15.9, 36.8)];
        [bezierPath addCurveToPoint: CGPointMake(24.9, 21.9) controlPoint1: CGPointMake(19.5, 28.5) controlPoint2: CGPointMake(21.9, 24.9)];
        [bezierPath addCurveToPoint: CGPointMake(35.7, 14.7) controlPoint1: CGPointMake(27.9, 18.9) controlPoint2: CGPointMake(31.5, 16.5)];
        [bezierPath addCurveToPoint: CGPointMake(48.8, 12) controlPoint1: CGPointMake(39.9, 12.9) controlPoint2: CGPointMake(44.3, 12)];
        [bezierPath addCurveToPoint: CGPointMake(61.9, 14.7) controlPoint1: CGPointMake(53.4, 12) controlPoint2: CGPointMake(57.8, 12.9)];
        [bezierPath addCurveToPoint: CGPointMake(72.7, 21.9) controlPoint1: CGPointMake(66, 16.5) controlPoint2: CGPointMake(69.7, 18.9)];
        [bezierPath addCurveToPoint: CGPointMake(79.9, 32.7) controlPoint1: CGPointMake(75.7, 24.9) controlPoint2: CGPointMake(78.1, 28.5)];
        [bezierPath addCurveToPoint: CGPointMake(82.6, 45.8) controlPoint1: CGPointMake(81.7, 36.9) controlPoint2: CGPointMake(82.6, 41.3)];
        [bezierPath addCurveToPoint: CGPointMake(76.6, 65) controlPoint1: CGPointMake(82.6, 52.9) controlPoint2: CGPointMake(80.6, 59.2)];
        [bezierPath addLineToPoint: CGPointMake(93.1, 81.5)];
        [bezierPath addCurveToPoint: CGPointMake(95, 85.8) controlPoint1: CGPointMake(94.4, 82.7) controlPoint2: CGPointMake(95, 84.1)];
        [bezierPath closePath];
        [bezierPath moveToPoint: CGPointMake(64.1, 61.1)];
        [bezierPath addCurveToPoint: CGPointMake(70.4, 45.9) controlPoint1: CGPointMake(68.3, 56.9) controlPoint2: CGPointMake(70.4, 51.8)];
        [bezierPath addCurveToPoint: CGPointMake(64.1, 30.7) controlPoint1: CGPointMake(70.4, 40) controlPoint2: CGPointMake(68.3, 34.9)];
        [bezierPath addCurveToPoint: CGPointMake(48.9, 24.4) controlPoint1: CGPointMake(59.9, 26.5) controlPoint2: CGPointMake(54.8, 24.4)];
        [bezierPath addCurveToPoint: CGPointMake(33.7, 30.7) controlPoint1: CGPointMake(43, 24.4) controlPoint2: CGPointMake(37.9, 26.5)];
        [bezierPath addCurveToPoint: CGPointMake(27.4, 45.9) controlPoint1: CGPointMake(29.5, 34.9) controlPoint2: CGPointMake(27.4, 40)];
        [bezierPath addCurveToPoint: CGPointMake(33.7, 61.1) controlPoint1: CGPointMake(27.4, 51.8) controlPoint2: CGPointMake(29.5, 56.9)];
        [bezierPath addCurveToPoint: CGPointMake(48.9, 67.4) controlPoint1: CGPointMake(37.9, 65.3) controlPoint2: CGPointMake(43, 67.4)];
        [bezierPath addCurveToPoint: CGPointMake(64.1, 61.1) controlPoint1: CGPointMake(54.8, 67.4) controlPoint2: CGPointMake(59.8, 65.3)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [color4 setFill];
        [bezierPath fill];
    }
}

+ (void)drawCanvas11;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(45.9, 14.1)];
    [bezierPath addLineToPoint: CGPointMake(58.1, 38.8)];
    [bezierPath addLineToPoint: CGPointMake(85.4, 42.8)];
    [bezierPath addLineToPoint: CGPointMake(65.6, 62.1)];
    [bezierPath addLineToPoint: CGPointMake(70.3, 89.3)];
    [bezierPath addLineToPoint: CGPointMake(45.9, 76.4)];
    [bezierPath addLineToPoint: CGPointMake(21.5, 89.3)];
    [bezierPath addLineToPoint: CGPointMake(26.1, 62.1)];
    [bezierPath addLineToPoint: CGPointMake(6.4, 42.8)];
    [bezierPath addLineToPoint: CGPointMake(33.7, 38.8)];
    [bezierPath addLineToPoint: CGPointMake(45.9, 14.1)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

+ (void)drawCanvas12;
{

    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(80, 36)];
        [bezierPath addLineToPoint: CGPointMake(28, 36)];
        [bezierPath addCurveToPoint: CGPointMake(25.4, 38.6) controlPoint1: CGPointMake(26.6, 36) controlPoint2: CGPointMake(25.4, 37.2)];
        [bezierPath addLineToPoint: CGPointMake(29, 91.2)];
        [bezierPath addCurveToPoint: CGPointMake(31.6, 94) controlPoint1: CGPointMake(29, 92.6) controlPoint2: CGPointMake(30.1, 94)];
        [bezierPath addLineToPoint: CGPointMake(76, 94)];
        [bezierPath addCurveToPoint: CGPointMake(78.6, 91.2) controlPoint1: CGPointMake(77.4, 94) controlPoint2: CGPointMake(78.6, 92.6)];
        [bezierPath addLineToPoint: CGPointMake(82.7, 38.7)];
        [bezierPath addCurveToPoint: CGPointMake(80, 36) controlPoint1: CGPointMake(82.5, 37.3) controlPoint2: CGPointMake(81.4, 36)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(84.8, 22)];
        [bezier2Path addLineToPoint: CGPointMake(85.1, 22)];
        [bezier2Path addCurveToPoint: CGPointMake(69.6, 21.4) controlPoint1: CGPointMake(85.1, 22) controlPoint2: CGPointMake(79.6, 22)];
        [bezier2Path addLineToPoint: CGPointMake(65.8, 14)];
        [bezier2Path addLineToPoint: CGPointMake(41.8, 14)];
        [bezier2Path addLineToPoint: CGPointMake(38.4, 21.8)];
        [bezier2Path addCurveToPoint: CGPointMake(23.8, 23.1) controlPoint1: CGPointMake(29.7, 22.4) controlPoint2: CGPointMake(24.7, 22.9)];
        [bezier2Path addLineToPoint: CGPointMake(23.4, 23)];
        [bezier2Path addCurveToPoint: CGPointMake(21, 25.4) controlPoint1: CGPointMake(22, 23) controlPoint2: CGPointMake(21, 24)];
        [bezier2Path addLineToPoint: CGPointMake(21, 26.7)];
        [bezier2Path addCurveToPoint: CGPointMake(23.3, 30) controlPoint1: CGPointMake(21, 28.1) controlPoint2: CGPointMake(21.9, 30)];
        [bezier2Path addLineToPoint: CGPointMake(84.8, 30)];
        [bezier2Path addCurveToPoint: CGPointMake(87, 26.7) controlPoint1: CGPointMake(86.2, 30) controlPoint2: CGPointMake(87, 28.1)];
        [bezier2Path addLineToPoint: CGPointMake(87, 25.4)];
        [bezier2Path addCurveToPoint: CGPointMake(84.8, 22) controlPoint1: CGPointMake(87, 24) controlPoint2: CGPointMake(86.2, 22)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];
    }
}

+ (void)drawCanvas13;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(90.67, 25.8)];
    [bezierPath addLineToPoint: CGPointMake(27.97, 25.8)];
    [bezierPath addCurveToPoint: CGPointMake(17.97, 31.5) controlPoint1: CGPointMake(23.37, 25.8) controlPoint2: CGPointMake(17.97, 27)];
    [bezierPath addLineToPoint: CGPointMake(17.97, 72.8)];
    [bezierPath addCurveToPoint: CGPointMake(27.97, 81.8) controlPoint1: CGPointMake(17.97, 77.4) controlPoint2: CGPointMake(23.37, 81.8)];
    [bezierPath addLineToPoint: CGPointMake(59.87, 81.8)];
    [bezierPath addLineToPoint: CGPointMake(59.87, 100.2)];
    [bezierPath addLineToPoint: CGPointMake(82.97, 81.8)];
    [bezierPath addLineToPoint: CGPointMake(90.57, 81.8)];
    [bezierPath addCurveToPoint: CGPointMake(98.07, 72.8) controlPoint1: CGPointMake(95.17, 81.8) controlPoint2: CGPointMake(98.07, 77.3)];
    [bezierPath addLineToPoint: CGPointMake(98.07, 31.5)];
    [bezierPath addCurveToPoint: CGPointMake(90.67, 25.8) controlPoint1: CGPointMake(97.97, 27) controlPoint2: CGPointMake(95.27, 25.8)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(38.67, 60.5)];
    [bezierPath addCurveToPoint: CGPointMake(30.67, 52.5) controlPoint1: CGPointMake(34.27, 60.5) controlPoint2: CGPointMake(30.67, 56.9)];
    [bezierPath addCurveToPoint: CGPointMake(38.67, 44.5) controlPoint1: CGPointMake(30.67, 48.1) controlPoint2: CGPointMake(34.27, 44.5)];
    [bezierPath addCurveToPoint: CGPointMake(46.67, 52.5) controlPoint1: CGPointMake(43.07, 44.5) controlPoint2: CGPointMake(46.67, 48.1)];
    [bezierPath addCurveToPoint: CGPointMake(38.67, 60.5) controlPoint1: CGPointMake(46.67, 56.9) controlPoint2: CGPointMake(43.17, 60.5)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(58.97, 60.5)];
    [bezierPath addCurveToPoint: CGPointMake(50.97, 52.5) controlPoint1: CGPointMake(54.57, 60.5) controlPoint2: CGPointMake(50.97, 56.9)];
    [bezierPath addCurveToPoint: CGPointMake(58.97, 44.5) controlPoint1: CGPointMake(50.97, 48.1) controlPoint2: CGPointMake(54.57, 44.5)];
    [bezierPath addCurveToPoint: CGPointMake(66.97, 52.5) controlPoint1: CGPointMake(63.37, 44.5) controlPoint2: CGPointMake(66.97, 48.1)];
    [bezierPath addCurveToPoint: CGPointMake(58.97, 60.5) controlPoint1: CGPointMake(66.97, 56.9) controlPoint2: CGPointMake(63.37, 60.5)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(78.07, 60.5)];
    [bezierPath addCurveToPoint: CGPointMake(70.07, 52.5) controlPoint1: CGPointMake(73.67, 60.5) controlPoint2: CGPointMake(70.07, 56.9)];
    [bezierPath addCurveToPoint: CGPointMake(78.07, 44.5) controlPoint1: CGPointMake(70.07, 48.1) controlPoint2: CGPointMake(73.67, 44.5)];
    [bezierPath addCurveToPoint: CGPointMake(86.07, 52.5) controlPoint1: CGPointMake(82.47, 44.5) controlPoint2: CGPointMake(86.07, 48.1)];
    [bezierPath addCurveToPoint: CGPointMake(78.07, 60.5) controlPoint1: CGPointMake(86.07, 56.9) controlPoint2: CGPointMake(82.47, 60.5)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

+ (void)drawCanvas14;
{

    //// Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(48.55, 17.39)];
        [bezierPath addCurveToPoint: CGPointMake(74.65, 26.29) controlPoint1: CGPointMake(57.75, 16.79) controlPoint2: CGPointMake(67.15, 19.69)];
        [bezierPath addCurveToPoint: CGPointMake(77.95, 77.09) controlPoint1: CGPointMake(89.55, 39.39) controlPoint2: CGPointMake(91.05, 62.19)];
        [bezierPath addCurveToPoint: CGPointMake(27.15, 80.39) controlPoint1: CGPointMake(64.85, 91.99) controlPoint2: CGPointMake(42.05, 93.49)];
        [bezierPath addCurveToPoint: CGPointMake(14.95, 53.29) controlPoint1: CGPointMake(19.05, 73.19) controlPoint2: CGPointMake(14.95, 63.29)];
        [bezierPath addLineToPoint: CGPointMake(23.95, 53.29)];
        [bezierPath addCurveToPoint: CGPointMake(24.05, 55.09) controlPoint1: CGPointMake(23.95, 53.89) controlPoint2: CGPointMake(23.95, 54.49)];
        [bezierPath addCurveToPoint: CGPointMake(33.15, 73.59) controlPoint1: CGPointMake(24.55, 62.29) controlPoint2: CGPointMake(27.75, 68.89)];
        [bezierPath addCurveToPoint: CGPointMake(52.65, 80.29) controlPoint1: CGPointMake(38.55, 78.39) controlPoint2: CGPointMake(45.55, 80.69)];
        [bezierPath addCurveToPoint: CGPointMake(71.15, 71.19) controlPoint1: CGPointMake(59.85, 79.79) controlPoint2: CGPointMake(66.45, 76.59)];
        [bezierPath addCurveToPoint: CGPointMake(77.85, 51.69) controlPoint1: CGPointMake(75.95, 65.79) controlPoint2: CGPointMake(78.25, 58.79)];
        [bezierPath addCurveToPoint: CGPointMake(68.75, 33.19) controlPoint1: CGPointMake(77.35, 44.49) controlPoint2: CGPointMake(74.15, 37.89)];
        [bezierPath addCurveToPoint: CGPointMake(49.25, 26.49) controlPoint1: CGPointMake(63.35, 28.39) controlPoint2: CGPointMake(56.35, 26.09)];
        [bezierPath addLineToPoint: CGPointMake(49.65, 33.09)];
        [bezierPath addLineToPoint: CGPointMake(29.85, 22.79)];
        [bezierPath addLineToPoint: CGPointMake(48.15, 11.29)];
        [bezierPath addLineToPoint: CGPointMake(48.55, 17.39)];
        [bezierPath closePath];
        bezierPath.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezierPath fill];
    }
}

+ (void)drawCanvas15;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(75.35, 83.21)];
    [bezierPath addCurveToPoint: CGPointMake(72.95, 77.61) controlPoint1: CGPointMake(75.45, 81.11) controlPoint2: CGPointMake(74.25, 79.11)];
    [bezierPath addCurveToPoint: CGPointMake(65.55, 71.81) controlPoint1: CGPointMake(70.85, 75.21) controlPoint2: CGPointMake(68.25, 73.41)];
    [bezierPath addCurveToPoint: CGPointMake(53.25, 66.41) controlPoint1: CGPointMake(61.65, 69.61) controlPoint2: CGPointMake(57.55, 67.81)];
    [bezierPath addCurveToPoint: CGPointMake(51.85, 65.01) controlPoint1: CGPointMake(52.55, 66.21) controlPoint2: CGPointMake(52.25, 65.61)];
    [bezierPath addCurveToPoint: CGPointMake(51.05, 58.61) controlPoint1: CGPointMake(50.75, 63.11) controlPoint2: CGPointMake(50.55, 60.71)];
    [bezierPath addCurveToPoint: CGPointMake(51.55, 57.21) controlPoint1: CGPointMake(51.15, 58.11) controlPoint2: CGPointMake(51.25, 57.61)];
    [bezierPath addCurveToPoint: CGPointMake(60.15, 40.21) controlPoint1: CGPointMake(55.95, 52.51) controlPoint2: CGPointMake(59.05, 46.51)];
    [bezierPath addCurveToPoint: CGPointMake(58.95, 27.91) controlPoint1: CGPointMake(60.85, 36.11) controlPoint2: CGPointMake(60.55, 31.81)];
    [bezierPath addCurveToPoint: CGPointMake(52.65, 20.21) controlPoint1: CGPointMake(57.65, 24.81) controlPoint2: CGPointMake(55.45, 22.11)];
    [bezierPath addCurveToPoint: CGPointMake(39.85, 17.51) controlPoint1: CGPointMake(48.95, 17.81) controlPoint2: CGPointMake(44.35, 16.91)];
    [bezierPath addCurveToPoint: CGPointMake(32.15, 20.31) controlPoint1: CGPointMake(37.15, 17.81) controlPoint2: CGPointMake(34.45, 18.81)];
    [bezierPath addCurveToPoint: CGPointMake(25.95, 28.01) controlPoint1: CGPointMake(29.35, 22.11) controlPoint2: CGPointMake(27.25, 24.91)];
    [bezierPath addCurveToPoint: CGPointMake(25.05, 41.51) controlPoint1: CGPointMake(24.25, 32.31) controlPoint2: CGPointMake(24.15, 37.01)];
    [bezierPath addCurveToPoint: CGPointMake(33.25, 57.41) controlPoint1: CGPointMake(26.25, 47.41) controlPoint2: CGPointMake(29.15, 53.01)];
    [bezierPath addCurveToPoint: CGPointMake(31.55, 66.01) controlPoint1: CGPointMake(34.55, 60.21) controlPoint2: CGPointMake(33.85, 63.91)];
    [bezierPath addCurveToPoint: CGPointMake(30.05, 66.71) controlPoint1: CGPointMake(31.15, 66.41) controlPoint2: CGPointMake(30.55, 66.51)];
    [bezierPath addCurveToPoint: CGPointMake(18.25, 72.41) controlPoint1: CGPointMake(25.95, 68.21) controlPoint2: CGPointMake(21.95, 70.11)];
    [bezierPath addCurveToPoint: CGPointMake(11.85, 77.51) controlPoint1: CGPointMake(15.95, 73.81) controlPoint2: CGPointMake(13.75, 75.41)];
    [bezierPath addCurveToPoint: CGPointMake(9.55, 81.41) controlPoint1: CGPointMake(10.85, 78.61) controlPoint2: CGPointMake(9.95, 79.91)];
    [bezierPath addCurveToPoint: CGPointMake(9.25, 85.21) controlPoint1: CGPointMake(9.15, 82.61) controlPoint2: CGPointMake(9.35, 84.01)];
    [bezierPath addCurveToPoint: CGPointMake(10.55, 89.31) controlPoint1: CGPointMake(9.15, 86.71) controlPoint2: CGPointMake(9.65, 88.11)];
    [bezierPath addCurveToPoint: CGPointMake(15.75, 92.91) controlPoint1: CGPointMake(11.85, 91.01) controlPoint2: CGPointMake(13.85, 92.11)];
    [bezierPath addCurveToPoint: CGPointMake(26.05, 95.41) controlPoint1: CGPointMake(19.05, 94.21) controlPoint2: CGPointMake(22.55, 94.91)];
    [bezierPath addCurveToPoint: CGPointMake(41.95, 96.31) controlPoint1: CGPointMake(31.35, 96.11) controlPoint2: CGPointMake(36.65, 96.31)];
    [bezierPath addCurveToPoint: CGPointMake(60.55, 95.11) controlPoint1: CGPointMake(48.15, 96.31) controlPoint2: CGPointMake(54.35, 96.11)];
    [bezierPath addCurveToPoint: CGPointMake(70.35, 92.21) controlPoint1: CGPointMake(63.95, 94.51) controlPoint2: CGPointMake(67.25, 93.71)];
    [bezierPath addCurveToPoint: CGPointMake(74.85, 87.81) controlPoint1: CGPointMake(72.25, 91.21) controlPoint2: CGPointMake(74.05, 89.81)];
    [bezierPath addCurveToPoint: CGPointMake(75.35, 83.21) controlPoint1: CGPointMake(75.55, 86.31) controlPoint2: CGPointMake(75.35, 84.81)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

+ (void)drawCanvas16;
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(78.82, 43.15)];
    [bezierPath addCurveToPoint: CGPointMake(61.52, 61.15) controlPoint1: CGPointMake(69.22, 43.15) controlPoint2: CGPointMake(61.52, 51.55)];
    [bezierPath addCurveToPoint: CGPointMake(63.32, 69.65) controlPoint1: CGPointMake(61.52, 63.95) controlPoint2: CGPointMake(62.22, 65.65)];
    [bezierPath addLineToPoint: CGPointMake(48.92, 69.65)];
    [bezierPath addCurveToPoint: CGPointMake(50.72, 61.15) controlPoint1: CGPointMake(50.12, 65.65) controlPoint2: CGPointMake(50.72, 63.95)];
    [bezierPath addCurveToPoint: CGPointMake(33.42, 43.45) controlPoint1: CGPointMake(50.72, 51.55) controlPoint2: CGPointMake(42.92, 43.45)];
    [bezierPath addCurveToPoint: CGPointMake(16.12, 60.65) controlPoint1: CGPointMake(23.92, 43.45) controlPoint2: CGPointMake(16.12, 51.05)];
    [bezierPath addCurveToPoint: CGPointMake(34.12, 77.85) controlPoint1: CGPointMake(16.12, 70.25) controlPoint2: CGPointMake(24.52, 77.85)];
    [bezierPath addCurveToPoint: CGPointMake(35.02, 77.75) controlPoint1: CGPointMake(34.22, 77.85) controlPoint2: CGPointMake(35.02, 77.75)];
    [bezierPath addLineToPoint: CGPointMake(35.02, 77.65)];
    [bezierPath addLineToPoint: CGPointMake(78.82, 77.65)];
    [bezierPath addCurveToPoint: CGPointMake(96.12, 60.45) controlPoint1: CGPointMake(88.42, 77.65) controlPoint2: CGPointMake(96.12, 69.95)];
    [bezierPath addCurveToPoint: CGPointMake(78.82, 43.15) controlPoint1: CGPointMake(96.12, 50.95) controlPoint2: CGPointMake(88.42, 43.15)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(25.92, 60.45)];
    [bezierPath addCurveToPoint: CGPointMake(33.42, 52.95) controlPoint1: CGPointMake(25.92, 56.25) controlPoint2: CGPointMake(29.32, 52.95)];
    [bezierPath addCurveToPoint: CGPointMake(40.92, 60.45) controlPoint1: CGPointMake(37.52, 52.95) controlPoint2: CGPointMake(40.92, 56.35)];
    [bezierPath addCurveToPoint: CGPointMake(33.42, 67.95) controlPoint1: CGPointMake(40.92, 64.65) controlPoint2: CGPointMake(37.52, 67.95)];
    [bezierPath addCurveToPoint: CGPointMake(25.92, 60.45) controlPoint1: CGPointMake(29.32, 67.95) controlPoint2: CGPointMake(25.92, 64.65)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(78.82, 68.05)];
    [bezierPath addCurveToPoint: CGPointMake(71.32, 60.55) controlPoint1: CGPointMake(74.62, 68.05) controlPoint2: CGPointMake(71.32, 64.65)];
    [bezierPath addCurveToPoint: CGPointMake(78.82, 53.05) controlPoint1: CGPointMake(71.32, 56.35) controlPoint2: CGPointMake(74.72, 53.05)];
    [bezierPath addCurveToPoint: CGPointMake(86.32, 60.55) controlPoint1: CGPointMake(82.92, 53.05) controlPoint2: CGPointMake(86.32, 56.45)];
    [bezierPath addCurveToPoint: CGPointMake(78.82, 68.05) controlPoint1: CGPointMake(86.42, 64.65) controlPoint2: CGPointMake(83.02, 68.05)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezierPath fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfSpeakerButtonWithSpeakerFrame: (CGRect)speakerFrame speakerIsSelected: (BOOL)speakerIsSelected;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(195, 70), NO, 0.0f);
    [JCStyleKit drawSpeakerButtonWithSpeakerFrame: speakerFrame speakerIsSelected: speakerIsSelected];
    UIImage* imageOfSpeakerButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfSpeakerButton;
}

+ (UIImage*)imageOfTrashButtonWithOuterFrame: (CGRect)outerFrame selectWithDeleteColor: (BOOL)selectWithDeleteColor;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(82, 70), NO, 0.0f);
    [JCStyleKit drawTrashButtonWithOuterFrame: outerFrame selectWithDeleteColor: selectWithDeleteColor];
    UIImage* imageOfTrashButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTrashButton;
}

@end
