//
//  JCStyleKit.h
//  JC
//
//  Created by Doug Leonard on 6/23/14.
//  Copyright (c) 2014 Jive. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface JCStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* moreIconLoginTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* voicemailLoginTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* defaultAvatarLoginTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* voicemailIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* speakerButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* trashButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* addIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas5Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* back_buttonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* directoryIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* locationIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* chatIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* scrubberIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* searchIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* starIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* trashIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* typingIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* undoIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* logoutIconTargets;

// Colors
+ (UIColor*)unSelectedColor;
+ (UIColor*)selectedColor;
+ (UIColor*)deleteColor;
+ (UIColor*)loginColor;

// Drawing Methods
+ (void)drawMoreIconLogin;
+ (void)drawVoicemailLogin;
+ (void)drawDefaultAvatarLogin;
+ (void)drawVoicemailIcon;
+ (void)drawComposeIconWithFrame: (CGRect)frame;
+ (void)drawSpeakerButtonWithSpeakerFrame: (CGRect)speakerFrame;
+ (void)drawPlay_PauseWithFrame: (CGRect)frame playPauseDisplaysPlay: (BOOL)playPauseDisplaysPlay;
+ (void)drawTrashButtonWithOuterFrame: (CGRect)outerFrame selectWithDeleteColor: (BOOL)selectWithDeleteColor;
+ (void)drawAddIconWithAddFrame: (CGRect)addFrame;
+ (void)drawCanvas5WithFrame: (CGRect)frame;
+ (void)drawBack_buttonWithFrame: (CGRect)frame;
+ (void)drawDirectoryIconWithFrame: (CGRect)frame;
+ (void)drawLocationIconWithFrame: (CGRect)frame;
+ (void)drawChatIconWithFrame: (CGRect)frame;
+ (void)drawScrubberIconWithFrame: (CGRect)frame;
+ (void)drawSearchIconWithFrame: (CGRect)frame;
+ (void)drawStarIconWithFrame: (CGRect)frame;
+ (void)drawTrashIconWithFrame: (CGRect)frame;
+ (void)drawTypingIconWithFrame: (CGRect)frame;
+ (void)drawUndoIconWithFrame: (CGRect)frame;
+ (void)drawLogoutIconWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfMoreIconLogin;
+ (UIImage*)imageOfVoicemailLogin;
+ (UIImage*)imageOfDefaultAvatarLogin;
+ (UIImage*)imageOfVoicemailIcon;
+ (UIImage*)imageOfSpeakerButtonWithSpeakerFrame: (CGRect)speakerFrame;
+ (UIImage*)imageOfTrashButtonWithOuterFrame: (CGRect)outerFrame selectWithDeleteColor: (BOOL)selectWithDeleteColor;
+ (UIImage*)imageOfAddIconWithAddFrame: (CGRect)addFrame;
+ (UIImage*)imageOfCanvas5WithFrame: (CGRect)frame;
+ (UIImage*)imageOfBack_buttonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfDirectoryIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfLocationIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfChatIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfScrubberIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfSearchIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfStarIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfTrashIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfTypingIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfUndoIconWithFrame: (CGRect)frame;
+ (UIImage*)imageOfLogoutIconWithFrame: (CGRect)frame;

@end
